### PR TITLE
#54 worker building upgrade

### PR DESCRIPTION
**Pull request by Bazsi1224**

### CODE REVIEW

**Comment by Bazsi1224** [comment]
#54 
- currently selected workers automatically get a new construct order on construction site placement

#55 is also done
- structures got a new property pair : progress and progress_max
- construction command now ads a value to progress, and when it reaches progress_max then the construction is finished
- HP bar show progress, when there is progress, and progress is less the progress max

**Comment by Scony** [comment]
Sounds good. I'll review it in the upcoming days.

Btw. Next time please consider opening one PR per change - it will be easier to track changes this way :)

**Comment by Scony** [comment]
I've started integrating above changes on the [non-immediate-constructing](https://github.com/lampe-games/godot-open-rts/tree/non-immediate-constructing) branch

**Comment by Scony** [comment]
Changes merged via https://github.com/lampe-games/godot-open-rts/tree/non-immediate-constructing branch, thanks!

**Pull request closed without merging**
