### PR TITLE
Rotate map with keyboard keys? #90

### PR DESCRIPTION
**Pull request by williamsokol**
Added keyboard controls to rotate the in game isometric camera. 
Currently using the default keys of Q and E.

If you try to use the mouse rotation at the same time, then keyboard controls take priority

### CODE REVIEW

**Comment by williamsokol** [comment]
no sure why it is failing, when I run gdformat on my pc it works fine

**Comment by Scony** [comment]
@williamsokol what version of `gdformat` do you have installed?

**Comment by williamsokol** [comment]
I used gdformat 4.2.0 to format code after I saw it was failing the static checks on this merge request. 

There were no issues when using it locally so i am not sure if the static check is using a different version or something else

**Comment by Scony** [comment]
Thanks!

**Pull request merged**
